name: Deploy to Render

on:
  push:
    branches:
      - main  # Se ejecuta cuando se hace push en la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          python manage.py migrate

      - name: Deploy to Render
        run: |
          # Añadir el comando para desplegar a Render (si Render ofrece un CLI para esto)
          # Por ejemplo:
          # curl -X POST https://api.render.com/deploy ...
